name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
    branches:
      - '*'

permissions:
  actions: write
  checks: write
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run Tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Library
        run: yarn build

  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tag')
    needs: build
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

      - name: Build Library
        run: yarn build

      - name: Publish to npm
        run: npm publish ./dist/angular-email-builder --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
